[package]
name = "git-memo"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
git2 = "0.20"
serde_json = "1"

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.0"
tempfile = "3"
